apiVersion: v1
kind: ConfigMap
metadata:
  name: my-kafkachannel-broker
data:
  channelTemplateSpec: |-
    apiVersion: messaging.knative.dev/v1beta1
    kind: KafkaChannel
    spec:
        numPartitions: 1
        replicationFactor: 1
---
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  annotations:
    eventing.knative.dev/broker.class: MTChannelBasedBroker
  name: my-kafkachannel-broker
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: my-kafkachannel-broker
